# Generated by Django 5.2.16 on 2026-08-06 16:18

import uuid
from django.db import migrations, models


def assign_unique_legacy_emails(apps, schema_editor):
    user_model = apps.get_model('accounts', 'User')
    for user_id in user_model.objects.values_list('id', flat=True).iterator():
        user_model.objects.filter(pk=user_id).update(
            email=f'legacy-{user_id}@invalid.local',
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_seed_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_verified_at',
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(assign_unique_legacy_emails, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='EmailVerificationCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('purpose', models.CharField(choices=[('registration', '注册'), ('password_reset', '重置密码')], max_length=24)),
                ('code_hash', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_attempts', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'purpose', '-created_at'], name='email_code_lookup_idx')],
            },
        ),
    ]
