# Generated by Django 5.2.16 on 2026-08-03 17:32

import django.core.validators
import django.db.models.deletion
import modules.cases.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=40, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9][A-Z0-9_-]*$', '病例编号只能使用大写字母、数字、_ 和 -。')])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CaseVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布')], max_length=16)),
                ('version_number', models.PositiveIntegerField(blank=True, null=True)),
                ('title_internal', models.CharField(max_length=160)),
                ('title_student', models.CharField(max_length=160)),
                ('specialty', models.CharField(blank=True, max_length=80)),
                ('disease_tags', models.JSONField(blank=True, default=list)),
                ('difficulty', models.CharField(choices=[('basic', '基础'), ('intermediate', '中级'), ('advanced', '高级')], default='intermediate', max_length=16)),
                ('estimated_minutes', models.PositiveSmallIntegerField(default=20, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(240)])),
                ('teaching_objectives', models.TextField(blank=True)),
                ('target_grade', models.CharField(blank=True, max_length=80)),
                ('is_exam_mode', models.BooleanField(default=True)),
                ('time_limit_minutes', models.PositiveSmallIntegerField(default=20, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(240)])),
                ('enabled_stages', models.JSONField(default=modules.cases.models.default_enabled_stages)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('based_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='derived_versions', to='cases.caseversion')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='cases.case')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case_versions_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['case_id', 'status', 'version_number'],
            },
        ),
        migrations.CreateModel(
            name='CaseFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80)),
                ('category', models.CharField(choices=[('chief_complaint', '主诉'), ('present_illness', '现病史'), ('past_history', '既往史'), ('medication', '用药史'), ('allergy', '过敏史'), ('personal', '个人史'), ('family', '家族史'), ('concern', '患者担忧'), ('other', '其他')], max_length=32)),
                ('standard_fact', models.TextField()),
                ('patient_expression', models.TextField()),
                ('semantic_tags', models.JSONField(blank=True, default=list)),
                ('synonyms', models.JSONField(blank=True, default=list)),
                ('disclosure_mode', models.CharField(choices=[('active', '主动披露'), ('on_question', '被问到后披露'), ('never', '患者角色禁止披露')], default='on_question', max_length=24)),
                ('certainty', models.CharField(choices=[('certain', '确定'), ('vague', '模糊'), ('forgotten', '记不清'), ('not_understood', '不理解')], default='certain', max_length=24)),
                ('unknown_response', models.CharField(default='这个我不太清楚。', max_length=240)),
                ('is_required', models.BooleanField(default=False)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('teacher_notes', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='cases.caseversion')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosisRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis_type', models.CharField(choices=[('initial', '初步诊断'), ('differential', '鉴别诊断'), ('final', '最终诊断')], max_length=24)),
                ('name', models.CharField(max_length=160)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('supporting_evidence', models.JSONField(blank=True, default=list)),
                ('opposing_evidence', models.JSONField(blank=True, default=list)),
                ('is_required', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_rules', to='cases.caseversion')),
            ],
            options={
                'ordering': ['diagnosis_type', 'display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=80)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(120)])),
                ('sex', models.CharField(choices=[('female', '女'), ('male', '男'), ('other', '其他'), ('unspecified', '未说明')], default='unspecified', max_length=16)),
                ('occupation', models.CharField(blank=True, max_length=120)),
                ('education', models.CharField(blank=True, max_length=80)),
                ('personality', models.CharField(blank=True, max_length=160)),
                ('emotion', models.CharField(blank=True, max_length=120)),
                ('cooperation', models.CharField(blank=True, max_length=120)),
                ('medical_literacy', models.CharField(blank=True, max_length=120)),
                ('opening_statement', models.TextField(blank=True)),
                ('avatar_asset_id', models.CharField(blank=True, max_length=120)),
                ('voice_id', models.CharField(blank=True, max_length=120)),
                ('version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to='cases.caseversion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScoringItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80)),
                ('dimension', models.CharField(choices=[('history', '病史采集'), ('communication', '问诊逻辑与沟通'), ('summary', '病史摘要'), ('clinical', '临床表现描述'), ('differential', '鉴别诊断'), ('test_plan', '检查计划'), ('final_reasoning', '最终诊断与依据')], max_length=32)),
                ('label', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('evaluation_method', models.CharField(choices=[('rule', '规则评分'), ('ai', 'AI 辅助评价'), ('teacher', '教师评价')], default='rule', max_length=16)),
                ('matching_config', models.JSONField(blank=True, default=dict)),
                ('student_feedback', models.TextField(blank=True)),
                ('teacher_notes', models.TextField(blank=True)),
                ('is_student_visible', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_items', to='cases.caseversion')),
            ],
            options={
                'ordering': ['dimension', 'display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TestDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=160)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('student_description', models.TextField(blank=True)),
                ('result_text', models.TextField(blank=True)),
                ('teacher_interpretation', models.TextField(blank=True)),
                ('release_stage', models.CharField(choices=[('clinical_exam', '临床检查'), ('test_results', '辅助检查结果')], default='test_results', max_length=24)),
                ('requires_request', models.BooleanField(default=True)),
                ('prerequisite_code', models.CharField(blank=True, max_length=80)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='cases.caseversion')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='caseversion',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'draft')), fields=('case',), name='unique_draft_per_case'),
        ),
        migrations.AddConstraint(
            model_name='caseversion',
            constraint=models.UniqueConstraint(condition=models.Q(('version_number__isnull', False)), fields=('case', 'version_number'), name='unique_case_version_number'),
        ),
        migrations.AddConstraint(
            model_name='caseversion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'draft'), ('version_number__isnull', True)), models.Q(('status', 'published'), ('version_number__isnull', False)), _connector='OR'), name='case_version_status_number_consistent'),
        ),
        migrations.AddConstraint(
            model_name='casefact',
            constraint=models.UniqueConstraint(fields=('version', 'code'), name='unique_fact_code_version'),
        ),
        migrations.AddConstraint(
            model_name='scoringitem',
            constraint=models.UniqueConstraint(fields=('version', 'code'), name='unique_scoring_code_version'),
        ),
        migrations.AddConstraint(
            model_name='testdefinition',
            constraint=models.UniqueConstraint(fields=('version', 'code'), name='unique_test_code_version'),
        ),
    ]
