# Generated by Django 5.2.16 on 2026-08-07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def transfer_class_ownership(apps, schema_editor):
    class_group_model = apps.get_model('teaching', 'ClassGroup')
    course_model = apps.get_model('teaching', 'Course')
    owners = dict(course_model.objects.values_list('id', 'created_by_id'))
    used_codes = set()

    for class_group in class_group_model.objects.order_by('created_at', 'id').iterator():
        base_code = class_group.code
        candidate = base_code
        counter = 2
        while candidate in used_codes:
            suffix = f'-{counter}'
            candidate = f'{base_code[:40 - len(suffix)]}{suffix}'
            counter += 1
        used_codes.add(candidate)
        class_group.created_by_id = owners[class_group.course_id]
        class_group.code = candidate
        class_group.save(update_fields=['created_by', 'code'])


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classgroup',
            name='created_by',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='classes_created',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(transfer_class_ownership, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='classgroup',
            name='created_by',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='classes_created',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterModelOptions(
            name='classgroup',
            options={'ordering': ['code']},
        ),
        migrations.RemoveConstraint(
            model_name='classgroup',
            name='unique_class_code_course',
        ),
        migrations.AlterField(
            model_name='classgroup',
            name='code',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.DeleteModel(name='CourseTeacher'),
        migrations.RemoveField(model_name='classgroup', name='course'),
        migrations.DeleteModel(name='Course'),
    ]
