from django.urls import path

from .views import (
    StudentAssignmentListView,
    StudentPatientInitiativeActivateView,
    StudentPatientInitiativeTriggerView,
    StudentPhysicalExamAssetContentView,
    StudentSessionCompleteView,
    StudentSessionDetailView,
    StudentSessionDraftView,
    StudentSessionFeedbackView,
    StudentSessionMessageView,
    StudentSessionStartView,
    TeacherAssignmentCloseView,
    TeacherAssignmentCsvExportView,
    TeacherAssignmentListCreateView,
    TeacherAssignmentOptionView,
    TeacherAssignmentReleaseFeedbackView,
    TeacherAssignmentResponseListView,
    TeacherAssignmentStatisticsView,
    TeacherPhysicalExamAssetContentView,
    TeacherSessionAIEvaluationView,
    TeacherSessionRecordView,
    TeacherSessionReviewView,
)

urlpatterns = [
    path(
        "teacher/assignments/",
        TeacherAssignmentListCreateView.as_view(),
        name="teacher-assignment-list",
    ),
    path(
        "teacher/assignments/options/",
        TeacherAssignmentOptionView.as_view(),
        name="teacher-assignment-options",
    ),
    path(
        "teacher/assignments/<uuid:assignment_id>/close/",
        TeacherAssignmentCloseView.as_view(),
        name="teacher-assignment-close",
    ),
    path(
        "teacher/assignments/<uuid:assignment_id>/release-feedback/",
        TeacherAssignmentReleaseFeedbackView.as_view(),
        name="teacher-assignment-release-feedback",
    ),
    path(
        "teacher/assignments/<uuid:assignment_id>/responses/",
        TeacherAssignmentResponseListView.as_view(),
        name="teacher-assignment-responses",
    ),
    path(
        "teacher/assignments/<uuid:assignment_id>/statistics/",
        TeacherAssignmentStatisticsView.as_view(),
        name="teacher-assignment-statistics",
    ),
    path(
        "teacher/assignments/<uuid:assignment_id>/export.csv",
        TeacherAssignmentCsvExportView.as_view(),
        name="teacher-assignment-export-csv",
    ),
    path(
        "teacher/sessions/<uuid:session_id>/record/",
        TeacherSessionRecordView.as_view(),
        name="teacher-session-record",
    ),
    path(
        "teacher/sessions/<uuid:session_id>/physical-exam/assets/<int:asset_id>/content/",
        TeacherPhysicalExamAssetContentView.as_view(),
        name="teacher-session-physical-exam-asset-content",
    ),
    path(
        "teacher/sessions/<uuid:session_id>/reviews/",
        TeacherSessionReviewView.as_view(),
        name="teacher-session-review",
    ),
    path(
        "teacher/sessions/<uuid:session_id>/ai-evaluation/",
        TeacherSessionAIEvaluationView.as_view(),
        name="teacher-session-ai-evaluation",
    ),
    path(
        "student/assignments/",
        StudentAssignmentListView.as_view(),
        name="student-assignment-list",
    ),
    path(
        "student/assignments/<uuid:assignment_id>/session/",
        StudentSessionStartView.as_view(),
        name="student-session-start",
    ),
    path(
        "student/sessions/<uuid:session_id>/",
        StudentSessionDetailView.as_view(),
        name="student-session-detail",
    ),
    path(
        "student/sessions/<uuid:session_id>/messages/",
        StudentSessionMessageView.as_view(),
        name="student-session-message",
    ),
    path(
        "student/sessions/<uuid:session_id>/patient-initiative/activate/",
        StudentPatientInitiativeActivateView.as_view(),
        name="student-patient-initiative-activate",
    ),
    path(
        "student/sessions/<uuid:session_id>/patient-initiative/trigger/",
        StudentPatientInitiativeTriggerView.as_view(),
        name="student-patient-initiative-trigger",
    ),
    path(
        "student/sessions/<uuid:session_id>/physical-exam/assets/<int:asset_id>/content/",
        StudentPhysicalExamAssetContentView.as_view(),
        name="student-session-physical-exam-asset-content",
    ),
    path(
        "student/sessions/<uuid:session_id>/draft/",
        StudentSessionDraftView.as_view(),
        name="student-session-draft",
    ),
    path(
        "student/sessions/<uuid:session_id>/complete/",
        StudentSessionCompleteView.as_view(),
        name="student-session-complete",
    ),
    path(
        "student/sessions/<uuid:session_id>/feedback/",
        StudentSessionFeedbackView.as_view(),
        name="student-session-feedback",
    ),
]
