# Generated by Django 5.2.16 on 2026-08-04 14:51

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        ('teaching', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=160)),
                ('duration_minutes', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(240)])),
                ('opens_at', models.DateTimeField()),
                ('deadline_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('open', '进行中'), ('closed', '已收卷')], default='open', max_length=16)),
                ('feedback_released_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='cases.caseversion')),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case_assignments', to='teaching.classgroup')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case_assignments_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-opens_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignment_links', to=settings.AUTH_USER_MODEL)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_links', to='simulation.caseassignment')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('role', models.CharField(choices=[('student', '学生'), ('patient', '患者'), ('system', '系统')], max_length=16)),
                ('content', models.TextField()),
                ('client_message_id', models.CharField(blank=True, max_length=64)),
                ('response_status', models.CharField(choices=[('processing', '生成中'), ('completed', '已完成'), ('failed', '失败'), ('not_applicable', '不适用')], default='not_applicable', max_length=24)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('input_mode', models.CharField(default='text', max_length=16)),
                ('transcript', models.TextField(blank=True)),
                ('audio_asset_id', models.CharField(blank=True, max_length=120)),
                ('asr_confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reply_to', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patient_reply', to='simulation.message')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='SimulationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', '进行中'), ('completed', '已交卷'), ('expired', '已超时')], default='active', max_length=16)),
                ('stage', models.CharField(choices=[('interview', '问诊'), ('initial_reasoning', '初步判断'), ('test_selection', '检查选择'), ('final_reasoning', '最终判断'), ('completed', '已完成')], default='interview', max_length=32)),
                ('started_at', models.DateTimeField()),
                ('deadline_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('retention_expires_at', models.DateTimeField()),
                ('last_message_sequence', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='simulation.caseassignment')),
                ('case_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='cases.caseversion')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='simulation_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SessionStageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_stage', models.CharField(blank=True, max_length=32)),
                ('to_stage', models.CharField(choices=[('interview', '问诊'), ('initial_reasoning', '初步判断'), ('test_selection', '检查选择'), ('final_reasoning', '最终判断'), ('completed', '已完成')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_events', to='simulation.simulationsession')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ModelCall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=80)),
                ('model', models.CharField(max_length=120)),
                ('prompt_version', models.CharField(default='patient-v1', max_length=40)),
                ('request_hash', models.CharField(max_length=64)),
                ('matched_fact_codes', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('succeeded', '成功'), ('failed', '失败')], max_length=16)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generated_by_calls', to='simulation.message')),
                ('student_message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_calls', to='simulation.message')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_calls', to='simulation.simulationsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='message',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='simulation.simulationsession'),
        ),
        migrations.CreateModel(
            name='StageSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submission_type', models.CharField(choices=[('history_summary', '病史摘要'), ('initial_reasoning', '初步诊断和鉴别诊断'), ('test_selection', '检查计划'), ('final_reasoning', '最终诊断和处理原则')], max_length=32)),
                ('payload', models.JSONField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='simulation.simulationsession')),
            ],
            options={
                'ordering': ['submitted_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='caseassignment',
            constraint=models.CheckConstraint(condition=models.Q(('deadline_at__gt', models.F('opens_at'))), name='assignment_deadline_after_open'),
        ),
        migrations.AddConstraint(
            model_name='assignmentstudent',
            constraint=models.UniqueConstraint(fields=('assignment', 'student'), name='unique_assignment_student'),
        ),
        migrations.AddConstraint(
            model_name='simulationsession',
            constraint=models.UniqueConstraint(fields=('assignment', 'student'), name='one_attempt_per_assignment'),
        ),
        migrations.AddConstraint(
            model_name='simulationsession',
            constraint=models.CheckConstraint(condition=models.Q(('deadline_at__gt', models.F('started_at'))), name='session_deadline_after_start'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(fields=('session', 'sequence'), name='unique_message_sequence'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(condition=models.Q(('client_message_id', ''), _negated=True), fields=('session', 'client_message_id'), name='unique_session_client_message'),
        ),
        migrations.AddConstraint(
            model_name='stagesubmission',
            constraint=models.UniqueConstraint(fields=('session', 'submission_type'), name='unique_session_submission_type'),
        ),
    ]
