# Generated by Django 5.2.16 on 2026-08-04 15:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
        ('simulation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('automatic_score', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('scored_maximum', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('maximum_score', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('provisional', models.BooleanField(default=False)),
                ('omissions', models.JSONField(default=list)),
                ('errors', models.JSONField(default=list)),
                ('feedback_summary', models.TextField(blank=True)),
                ('ai_feedback', models.TextField(blank=True)),
                ('scoring_version', models.CharField(default='rules-v1', max_length=40)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='simulation.simulationsession')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=160)),
                ('label', models.CharField(max_length=240)),
                ('dimension', models.CharField(max_length=40)),
                ('evaluation_method', models.CharField(max_length=24)),
                ('automatic_score', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=8)),
                ('decision', models.CharField(choices=[('achieved', '已完成'), ('partial', '部分完成'), ('missed', '未完成'), ('pending', '待评价')], max_length=16)),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('evidence_message_ids', models.JSONField(default=list)),
                ('evidence_submission_ids', models.JSONField(default=list)),
                ('evidence_excerpt', models.TextField(blank=True)),
                ('standard_answer', models.TextField(blank=True)),
                ('reason', models.TextField()),
                ('is_student_visible', models.BooleanField(default=True)),
                ('rule_version', models.CharField(default='rules-v1', max_length=40)),
                ('model_version', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scoring_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='score_results', to='cases.scoringitem')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_results', to='simulation.simulationsession')),
            ],
            options={
                'ordering': ['dimension', 'code'],
                'constraints': [models.UniqueConstraint(fields=('session', 'code'), name='unique_session_score_code')],
            },
        ),
    ]
