# Generated by Django 5.2.16 on 2026-08-04 15:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0002_sessionassessment_scoreresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveIntegerField()),
                ('score_overrides', models.JSONField(default=dict)),
                ('comment', models.TextField(blank=True)),
                ('final_score', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('scored_maximum', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('maximum_score', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('provisional', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='simulation_reviews', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_reviews', to='simulation.simulationsession')),
            ],
            options={
                'ordering': ['revision'],
                'constraints': [models.UniqueConstraint(fields=('session', 'revision'), name='unique_session_review_revision')],
            },
        ),
    ]
