# Generated by Django 5.2.16 on 2026-08-04 16:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0003_teacherreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIEvaluationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('running', '评价中'), ('succeeded', '成功'), ('failed', '失败')], default='running', max_length=16)),
                ('provider', models.CharField(max_length=80)),
                ('model', models.CharField(max_length=120)),
                ('resolved_model', models.CharField(blank=True, max_length=120)),
                ('prompt_version', models.CharField(default='assessment-v1', max_length=40)),
                ('request_hash', models.CharField(max_length=64)),
                ('scoring_item_codes', models.JSONField(default=list)),
                ('feedback_summary', models.TextField(blank=True)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_ai_evaluations', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_evaluation_runs', to='simulation.simulationsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIScoreResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=2, max_digits=8)),
                ('decision', models.CharField(choices=[('achieved', '已完成'), ('partial', '部分完成'), ('missed', '未完成'), ('pending', '待评价')], max_length=16)),
                ('confidence', models.DecimalField(decimal_places=4, max_digits=5)),
                ('evidence_message_ids', models.JSONField(default=list)),
                ('evidence_submission_ids', models.JSONField(default=list)),
                ('evidence_excerpt', models.TextField(blank=True)),
                ('reason', models.TextField()),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='simulation.aievaluationrun')),
                ('score_result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_evaluations', to='simulation.scoreresult')),
            ],
            options={
                'ordering': ['score_result__dimension', 'score_result__code'],
            },
        ),
        migrations.AddConstraint(
            model_name='aievaluationrun',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'running')), fields=('session',), name='one_running_ai_evaluation_per_session'),
        ),
        migrations.AddConstraint(
            model_name='aiscoreresult',
            constraint=models.UniqueConstraint(fields=('run', 'score_result'), name='unique_ai_result_per_run_item'),
        ),
    ]
