# Generated by Django 5.2.16 on 2026-08-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulation", "0004_aievaluationrun_aiscoreresult_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caseassignment",
            name="status",
            field=models.CharField(
                choices=[("open", "进行中"), ("closed", "已结束")],
                default="open",
                max_length=16,
            ),
        ),
    ]
